// Created by Grigore Stefan <g_stefan@yahoo.com>
// Public domain (Unlicense) <http://unlicense.org>
// SPDX-FileCopyrightText: 2023-2026 Grigore Stefan <g_stefan@yahoo.com>
// SPDX-License-Identifier: Unlicense

Console.writeLn("Fabricare - Build system");
Console.writeLn("version " + Fabricare.getVersion());
Console.writeLn("usage: fabricare [options] [action]");
Console.writeLn("options:");
Console.writeLn("    --help                 this info");
Console.writeLn("    --usage                this info");
Console.writeLn("    --license              show license");
Console.writeLn("    --version              show version");
Console.writeLn("    --run-script=file      run script");
Console.writeLn("    --config=file          use config file, default .fabricare.json");
Console.writeLn("    --user-config=file     use user config file, default ~/.fabricare.json");
Console.writeLn("    --workspace=file       use workspace file, default fabricare.json");
Console.writeLn("    --platform=[platform]  select specified platform");
Console.writeLn("    --debug                debug build");
Console.writeLn("    --static               static build (dll-or-lib makes lib)");
Console.writeLn("    --spdx                 show SPDX license of projects and dependencies");
Console.writeLn("    @file                  read more arguments from file");
Console.writeLn("actions:");
Console.writeLn("    usage      this info");
Console.writeLn("    help       this info");
Console.writeLn("    default    same as make");
Console.writeLn("    clean      remove output and temp folders");
Console.writeLn("    make       build output folder");
Console.writeLn("    test       build and run test projects");
Console.writeLn("    version    bump build and date");
Console.writeLn("    install    install bin,include,lib folders");
Console.writeLn("    release    pack output folder to release folder");
Console.writeLn("    sdk-make   make, install, release and release-install");
Console.writeLn("    spdx       same as --spdx");
Console.writeLn("- related to make (xyo-cpp):");
Console.writeLn("    analyze               make with static analysis");
Console.writeLn("    dependency-version    show versions of dependencies");
Console.writeLn("- related to version:");
Console.writeLn("    version-major    bump major version");
Console.writeLn("    version-minor    bump minor version");
Console.writeLn("    version-patch    bump patch version");
Console.writeLn("- related to install:");
Console.writeLn("    install-bin             install only bin folder");
Console.writeLn("    install-from-release    install from current release");
Console.writeLn("    fabricare.self-install  install fabricare from a release bin folder");
Console.writeLn("- related to release:");
Console.writeLn("    release-extract    extract current release");
Console.writeLn("    release-remove     remove current release");
Console.writeLn("    release-install    copy current release to release repository");
Console.writeLn("    release-version    show release files of current version");
Console.writeLn("    release-exists     show if current release exists");
Console.writeLn("- related to git:");
Console.writeLn("    git-update                 update from/to git");
Console.writeLn("- related to github:");
Console.writeLn("    github-release                create and upload current release");
Console.writeLn("    github-release-download       download current release");
Console.writeLn("    github-release-keep-last-3    remove all releases older than last 3");
Console.writeLn("    github-release-remove-all     remove all releases");
Console.writeLn("    github-release-check          check release if exists");
Console.writeLn("- related to gitea:");
Console.writeLn("    gitea-release                create and upload current release");
Console.writeLn("    gitea-release-remove-all     remove all releases");
Console.writeLn("    gitea-release-download       download current release");
